### ISSUE TITLE
How to install this extension?

### ISSUE THREAD

**Issue by winko** [jniesen/build-flow-json-parser-extension-plugin#1]
Hi!
Could you add short description of how to install this useful extension?
Regards

**Comment by jniesen** [comment]
Totally! I'll look at it tonight.

I really just need to package and submit it so that you can install it
through the plugin manager.

**Comment by joris255** [comment]
Hello,
Is there any progress on this? If not, are there other ways to install your plugin "unpackaged"?

Regards

**Comment by jniesen** [comment]
Sorry for the lack of response. The readme has been updated with installation instructions.

**Comment by jniesen** [comment]
The request has gone out to have the plugin published. See [mailing list thread](https://groups.google.com/forum/#!topic/jenkinsci-dev/W7h1rEJ5fZE).

**Comment by joris255** [comment]
Thank you!
